#!/bin/sh

if [ -f /EON ] && [ ! -f qt/text ]; then
  cp qt/text_aarch64 qt/text
elif [ -f /TICI ] && [ ! -f qt/text ]; then
  cp qt/text_larch64 qt/text
elif [ -f /JETSON ] && [ ! -f qt/text ]; then
  cp qt/text_larch64 qt/text
fi

if [ ! -f /JETSON ]; then
export LD_LIBRARY_PATH="/system/lib64:$LD_LIBRARY_PATH"
fi
exec ./qt/text "$1"
if [ -f /TICI ]; then
  exec ./qt/text "$1"
else
  exec ./qt/text_c3 "$1"
fi
